# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0002_auto_20171111_1551'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='actors',
            field=models.ManyToManyField(related_name='performance_actor', to='actor.Actor'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='producer',
            field=models.ManyToManyField(related_name='performance_producer', to='actor.Actor'),
        ),
    ]
